name: Publish Package
on:
  push:
    tags:
      - "release-*"
env:
  ProjName: Shared

jobs:
  publish-package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Build
        run: dotnet build ${{ env.ProjName }}/${{ env.ProjName }}.csproj -o Out

      - name: Add GitHub NuGet Source
        run: dotnet nuget add source https://nuget.pkg.github.com/UplayEmus/index.json --name "github" --username "any" --password ${{ secrets.GITHUB_TOKEN  }} --store-password-in-clear-text
          
      - name: Publish to GitHub Packages
        run: dotnet nuget push Out/UplayEmus.${{ env.ProjName }}**.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN  }}
